-- V22: Fatia B — reativa isolamentos de BRAÇO (só dado). Substitui a antiga V22 (só antebraço).
-- O desmembramento ARMS → BICEPS/TRICEPS/FOREARMS tornou FOREARMS um TargetMuscle e deu peso próprio
-- a TRICEPS. Mas os 14 antebraços estavam invisíveis (modality=NULL) e o tríceps tinha só ~3-4
-- isolamentos visíveis em CASA. O match do motor é por `category` (já correto), então aqui só
-- preenchemos a taxonomia mínima p/ ficarem visíveis: STRENGTH, isolamento (is_compound=false),
-- movement_pattern=NONE (braço isolado não tem padrão composto), primary=[ARMS] (contexto —
-- MuscleGroup não separa bi/tri/antebraço; o alvo do motor vem da category).

-- ============================================================================
-- 1) ANTEBRAÇO (FOREARMS) — 14 exercícios, todos estavam invisíveis.
-- ============================================================================

-- CASA (halteres)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=true  WHERE id='6492b12e-158a-5540-8a1e-311fa662e14e';  -- Flexão de Punho com Halteres (base casa)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='f9b4cfcf-d75e-501f-9c44-899cf394f0b7';  -- Flexão de Pulso Neutra Sentado com Halteres
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='f2578383-69d6-52f0-a2f1-e331d02c4aa3';  -- Rosca de Dedos com Halteres

-- CASA (peso corporal / acessório portátil)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BODYWEIGHT', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='3a17152c-357f-59f2-9b9f-5820707584aa';  -- Hand Grip
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BODYWEIGHT', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='0b9d0da0-2031-5a60-97f9-5342573e783c';  -- Rolinho de antebraço

-- ACADEMIA (barra / anilha)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=true  WHERE id='f567e86b-b5ac-551f-963e-2592d3b30c52';  -- Rosca de punho com barra (base academia)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='4b2e0279-1103-5be9-a0fd-9f8aaf5f2a76';  -- Rosca de Punho Reversa com Barra
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[],        is_base=false WHERE id='b66c7c5e-3af2-5b0c-bb3f-d8d617846b6f';  -- Rosca Inversa com Barra (braquiorradial)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='557be3ac-8eae-532c-9eca-2b1e5e678eb3';  -- Rosca de dedo com barra
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='366c1aaa-e85b-5b0b-aa8d-6cf5e47aefd7';  -- Rosca de Punho com Barra Atrás das Costas
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='e9eb1fc8-395e-5514-a1d6-b7688f1dbe41';  -- Rosca de Punho Pegada Neutra com Anilhas
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='6849665e-f2f8-5b7a-8c25-b91d5788ee67';  -- Flexão de Punho Reversa com Anilha
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BARBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='49e50355-8d22-54dc-a977-7b144018228d';  -- Flexão de Punho Reversa com Barra no Banco

-- ACADEMIA (cabo, unilateral)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='CABLE', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=true, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY['WRIST']::TEXT[], is_base=false WHERE id='b6110705-4ad4-5fec-9d1f-856babc28df5';  -- Flexão de Punho com Cabo em um Braço no Chão

-- ============================================================================
-- 2) TRÍCEPS — reforça a cobertura de CASA (era ~4 isolamentos; vai p/ ~9).
--    Só halteres/corporal; máquina/cabo já existem visíveis p/ academia.
-- ============================================================================
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=true  WHERE id='496e37d5-bcad-5bb1-920c-bcd78ebcd0e1';  -- Tríceps Francês com Halter Bilateral (base casa)
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='978a0c86-b093-53bb-8569-5069b344b14c';  -- Extensão de tríceps com haltere em pronação
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=true,  prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='226ad443-4f53-519b-98df-575ad6750c32';  -- Extensão de tríceps com haltere unilateral sentado
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='DUMBBELL', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='ee02839b-d65a-51be-bbbd-6bab3f7ff224';  -- Tríceps Testa com Banco Declinado com Halteres
UPDATE exercises SET modality='STRENGTH', movement_pattern='NONE', secondary_pattern=NULL, is_compound=false, equipment='BODYWEIGHT', primary_muscles=ARRAY['ARMS']::TEXT[], secondary_muscles=ARRAY[]::TEXT[], unilateral=false, prescription_type='REPS', level='BEGINNER', contraindications=ARRAY[]::TEXT[], is_base=false WHERE id='94c2c728-09da-51b9-838b-724d2020b90f';  -- Tríceps no Banco (dips no banco)

-- Resultado: FOREARMS 0→14 (casa 5). TRICEPS casa ~4→9. Bíceps já tinha 15 (casa 7).
