-- V30 (CANDIDATA — gerada por tools/curadoria/fix_curated.py).
-- Corrige a taxonomia dos exercícios JÁ CURADOS (auditoria técnica).
-- OPTIMISTIC UPDATE: cada statement só aplica se a coluna ainda tiver o valor auditado
-- (valor_atual). Se já foi corrigido por outra via, o UPDATE é no-op — não sobrescreve.
-- 176 correções em 126 exercícios.

UPDATE exercises SET equipment = 'BARBELL' WHERE name = 'Afundo com landmine' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'KETTLEBELL' WHERE name = 'Agachamento Goblet com Kettlebell e Faixa Elástica' AND equipment = 'BAND';
UPDATE exercises SET equipment = 'BARBELL' WHERE name = 'Agachamento no Landmine' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Airbike' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'BARBELL' WHERE name = 'Arranco de Potência' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Bicicleta Ergométrica Reclinada' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Bike' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'BODYWEIGHT' WHERE name = 'Dips na cadeira' AND equipment = 'MACHINE';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Esteira Ergométrica' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Esteira com Inclinação' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'MACHINE' WHERE name = 'Hands Bike' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'BODYWEIGHT' WHERE name = 'Paralelas entre Cadeiras' AND equipment = 'MACHINE';
UPDATE exercises SET equipment = 'CABLE' WHERE name = 'Pulldown com corda' AND equipment = 'MACHINE';
UPDATE exercises SET equipment = 'CABLE' WHERE name = 'Pulldown inclinado com corda' AND equipment = 'MACHINE';
UPDATE exercises SET equipment = 'CABLE' WHERE name = 'Tríceps pulley barra' AND equipment = 'BARBELL';
UPDATE exercises SET is_compound = false WHERE name = 'Cross over polia Alta' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Cross over polia baixa' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Flexão de Pernas com Faixa Elástica' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Flexão de pernas com toalha' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com Barra' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com Barra W Pegada invertida' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com Cabo' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com barra no banco declinado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com cabo sentado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover com haltere' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover de braço reto com halteres (joelhos a 90 graus)' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Pullover na Máquina de Alavanca' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Tríceps pulley barra' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Tríceps pulley corda' AND is_compound IS true;
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Agachamento Jefferson' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Agachamento com Barra Sobre a Cabeça' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Arranco com Barra' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Arranco com kettlebell de um braço' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Arranco com kettlebell em afundo' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Arranco de Potência' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Back Lever' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Bandeira Humana' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'INTERMEDIATE' WHERE name = 'Burpees' AND level = 'ADVANCED';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Flexão com parada de mãos' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Flexão com um braço' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Flexão de um braço com apoio' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'ADVANCED' WHERE name = 'Muscle Snatch' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Polichinelos' AND level = 'ADVANCED';
UPDATE exercises SET level = 'INTERMEDIATE' WHERE name = 'Salto na Caixa' AND level = 'ADVANCED';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Afundo com landmine' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento Pistola com Halteres' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento Pistola com Kettlebell' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento Pistola na Caixa' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento no Landmine' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento unilateral cruzado' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Agachamento unilateral cruzado com haltere' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Caminhada Lateral com Faixa de Resistência' AND prescription_type = 'DISTANCE';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Caminhada na Parede' AND prescription_type = 'DISTANCE';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Corrida Estacionária' AND prescription_type = 'DISTANCE';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Flexões hindu' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Remada com Halteres em Posição Prancha' AND prescription_type = 'TIME';
UPDATE exercises SET prescription_type = 'REPS' WHERE name = 'Salto em Uma Perna para a Frente' AND prescription_type = 'TIME';
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Agachamento com Barra Sobre a Cabeça' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Airbike' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['BACK']::TEXT[] WHERE name = 'Barra fixa com peso' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Bicicleta Ergométrica Reclinada' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Bike' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['CORE']::TEXT[] WHERE name = 'Cópia de Abdominal de Rã com Bola de Exercícios' AND primary_muscles = ARRAY['LEGS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['GLUTES']::TEXT[] WHERE name = 'Elevação Lateral de Perna com Faixa Elástica' AND primary_muscles = ARRAY['LEGS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Esteira Ergométrica' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Esteira com Inclinação' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['BACK']::TEXT[] WHERE name = 'Hands Bike' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Máquina Elíptica' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['LEGS']::TEXT[] WHERE name = 'Máquina Simulador Escada' AND primary_muscles = ARRAY['CORE']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['BACK']::TEXT[] WHERE name = 'Puxada Front Lever' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['BACK']::TEXT[] WHERE name = 'Remada Invertida Com Argolas' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['BACK']::TEXT[] WHERE name = 'Remada Invertida na Mesa' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET primary_muscles = ARRAY['CHEST']::TEXT[] WHERE name = 'Supino em Pé com Faixa Elástica' AND primary_muscles = ARRAY['SHOULDERS']::TEXT[];
UPDATE exercises SET unilateral = true WHERE name = 'Afundo' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo Lateral' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo Lateral com Barra' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo com Barra' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo com Gymstick' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo com Halteres' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo com landmine' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Afundo na Máquina Smith' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Agachamento Pistol com TRX' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Agachamento Pistola com Halteres' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Agachamento Pistola com Kettlebell' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Agachamento Pistola na Caixa' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Agachamento pistola' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Arranco com kettlebell em afundo' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Avanço com Joelho Alto em Cima da Bola Bosu' AND unilateral IS false;
UPDATE exercises SET unilateral = true WHERE name = 'Desenvolvimento militar de uma mão com kettlebell' AND unilateral IS false;
UPDATE exercises SET equipment = 'BOSU' WHERE name = 'Avanço com Joelho Alto em Cima da Bola Bosu' AND equipment = 'MEDICINE_BALL';
UPDATE exercises SET equipment = 'STABILITY_BALL' WHERE name = 'Flexão de Braço com Bola de Estabilidade' AND equipment = 'MEDICINE_BALL';
UPDATE exercises SET equipment = 'BOSU' WHERE name = 'Flexão de Braço no Bosu' AND equipment = 'BODYWEIGHT';
UPDATE exercises SET equipment = 'STABILITY_BALL' WHERE name = 'V-Up com Bola de Estabilidade' AND equipment = 'MEDICINE_BALL';
UPDATE exercises SET is_compound = false WHERE name = 'Abraços nos Joelhos em Pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Borboleta' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Dinâmico do Peitoral' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Inclinado Lateral em Pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Lateral da Parte Interna da Coxa' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Piriforme' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento Reverso de Pulso' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento assistido reverso (peitoral e ombro)' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento com PVC na Posição Frontal de Rack' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento da Esfinge' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de Adutores com Pernas Afastadas em Pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de Isquiotibiais deitado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de Punho' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de ombro com o braço cruzado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de quadril 90-90' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento de tríceps em pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento do Gastrocnêmio com Joelho Flexionado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento do Piriforme Sentado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento do peitoral e do ombro na porta' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento do trato iliotibial com rolo de espuma' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento dos Adutores em Posição Sentada com Pernas Abertas' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento dos Isquiotibiais Sentado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento dos adutores da coxa com rolo de espuma' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento dos flexores de quadril ajoelhado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento dos ombros por trás das costas' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamento em Pé dos Quadríceps' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Alongamentos de pés e tornozelos' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Catavento corporal' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Deslize de parede do serrátil com rolo de espuma' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Inclinação Lateral' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Inclinação Lateral em Pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Postura do Arco' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Postura do Bebê Feliz' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Postura do sapo' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rolagem de espuma para isquiotibiais' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rolamento de espuma nas costas' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rolamento de espuma nos quadríceps' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rolo de Espuma para os Glúteos' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rolo de espuma para fascite plantar' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rotação Externa do Pé com Faixa Elástica' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rotação Interna do Quadril Sentado com Faixa Elástica' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rotação da coluna torácica de joelhos' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Rotação espinhal deitado' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Toque Lateral dos Dedos dos Pés em Pé' AND is_compound IS true;
UPDATE exercises SET is_compound = false WHERE name = 'Torção Oblíqua Sentada' AND is_compound IS true;
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Deslize de parede do serrátil com rolo de espuma' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Postura do Arco' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Postura do Bebê Feliz' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Rolagem de espuma para isquiotibiais' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Rolamento de espuma nas costas' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Rolamento de espuma nos quadríceps' AND prescription_type = 'REPS';
UPDATE exercises SET prescription_type = 'TIME' WHERE name = 'Rolo de espuma para fascite plantar' AND prescription_type = 'REPS';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Borboleta' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Dinâmico do Peitoral' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Inclinado Lateral em Pé' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Lateral da Parte Interna da Coxa' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Piriforme' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Reverso de Pulso' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento Sentado para a Panturrilha com Perna Esticada' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento assistido reverso (peitoral e ombro)' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento com PVC na Posição Frontal de Rack' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento da Esfinge' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento da panturrilha agachado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento da panturrilha com descida do calcanhar' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de Adutores com Pernas Afastadas em Pé' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de Isquiotibiais deitado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de Punho' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de ombro com o braço cruzado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de panturrilha na parede' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de quadril 90-90' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento de tríceps em pé' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento do Gastrocnêmio com Joelho Flexionado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento do Piriforme Sentado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento do peitoral e do ombro na porta' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento do trato iliotibial com rolo de espuma' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento dos Adutores em Posição Sentada com Pernas Abertas' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento dos Isquiotibiais Sentado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento dos adutores da coxa com rolo de espuma' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento dos flexores de quadril ajoelhado' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento dos ombros por trás das costas' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamento em Pé dos Quadríceps' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Alongamentos de pés e tornozelos' AND level = 'INTERMEDIATE';
UPDATE exercises SET level = 'BEGINNER' WHERE name = 'Postura da Cobra - Alongamento Abdominal' AND level = 'INTERMEDIATE';
